# Generated by Django 5.2.1 on 2025-05-12 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('pcm', 'Pidgin')], default='en', max_length=10),
        ),
    ]
