# Generated by Django 5.2.1 on 2025-05-11 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.URLField(help_text='WhatsApp group invite link')),
                ('description', models.TextField()),
                ('is_national', models.BooleanField(default=False, help_text='Is this group for all states?')),
                ('state', models.CharField(blank=True, max_length=50)),
                ('lga', models.CharField(blank=True, help_text='Local Government Area or neighborhood', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('whatsapp_number', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=50)),
                ('lga', models.CharField(help_text='Local Government Area, Neighborhood or Estate', max_length=100)),
                ('occupation', models.CharField(max_length=100)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('yo', 'Yoruba'), ('pcm', 'Pidgin'), ('ha', 'Hausa'), ('ig', 'Igbo')], default='en', max_length=3)),
                ('joined_whatsapp_group', models.BooleanField(default=False)),
                ('categories_of_interest', models.ManyToManyField(related_name='interested_users', to='products.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('whatsapp_groups', models.ManyToManyField(blank=True, related_name='whatsapp_groups_joined', to='accounts.whatsappgroup')),
            ],
        ),
    ]
